# Generated by Django 3.2.4 on 2021-07-09 17:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('module_members', '0004_alter_member_id'),
        ('module_attendance', '0003_attendanceday_attendancesheet'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceCheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateField(blank=True, null=True)),
                ('check', models.BooleanField(null=True)),
                ('time_in', models.TimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='AttendanceMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attendance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='module_attendance.attendance')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='module_members.member')),
            ],
        ),
        migrations.DeleteModel(
            name='AttendanceSheet',
        ),
        migrations.AddField(
            model_name='attendancecheck',
            name='attendance_member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='module_attendance.attendancemember'),
        ),
    ]
