# Generated by Django 3.0.6 on 2021-06-06 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('module_tasks', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='priority',
        ),
        migrations.RemoveField(
            model_name='task',
            name='progress',
        ),
        migrations.AddField(
            model_name='task',
            name='task_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='task_status',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='task_time',
            field=models.TimeField(null=True),
        ),
    ]
