# Generated by Django 3.0.6 on 2021-06-06 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('module_tasks', '0002_auto_20210606_0752'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='task_status',
            field=models.BooleanField(null=True),
        ),
    ]
