# Generated by Django 3.0.6 on 2021-06-06 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('module_tasks', '0003_auto_20210606_0759'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='description',
            field=models.TextField(null=True),
        ),
    ]
