# Generated by Django 3.0.6 on 2021-05-09 21:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('module_students', '0002_student_photo'),
        ('module_fees', '0003_feesitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_code', models.CharField(blank=True, max_length=20)),
                ('payment_date', models.DateField(blank=True, null=True)),
                ('amount_paid', models.CharField(blank=True, max_length=15)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Profile')),
                ('fee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='module_fees.Fee')),
                ('student', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='module_students.Student')),
            ],
        ),
    ]
