# Generated by Django 3.2.4 on 2021-07-06 04:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('module_fees', '0007_auto_20210705_0531'),
        ('module_payments', '0002_alter_payment_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='fee',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='student',
        ),
        migrations.AddField(
            model_name='payment',
            name='bill',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='module_fees.bill'),
        ),
    ]
