# Generated by Django 3.2.4 on 2021-07-06 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('module_payments', '0003_auto_20210706_0442'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='amount_paid',
            new_name='amount_due',
        ),
        migrations.AddField(
            model_name='payment',
            name='payment',
            field=models.CharField(blank=True, max_length=15),
        ),
    ]
