# Generated by Django 3.2.4 on 2021-07-10 22:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('module_rooms', '0002_alter_room_id'),
        ('module_checkin', '0003_alter_checkin_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkin',
            name='room',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='module_rooms.room'),
        ),
    ]
