# Generated by Django 3.2.4 on 2021-07-12 17:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('module_workers', '0004_alter_worker_id'),
        ('module_roster', '0002_alter_roster_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_name', models.CharField(blank=True, max_length=100)),
                ('batch_symbol', models.CharField(blank=True, max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='RosterDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='roster',
            name='from_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='roster',
            name='to_date',
            field=models.DateField(null=True),
        ),
        migrations.CreateModel(
            name='WorkerPersonnel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='module_roster.batch')),
                ('roster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='module_roster.roster')),
                ('worker', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='module_workers.worker')),
            ],
        ),
        migrations.CreateModel(
            name='Shift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shift_name', models.CharField(blank=True, max_length=100)),
                ('start_time', models.TimeField(null=True)),
                ('end_time', models.TimeField(null=True)),
                ('roster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='module_roster.roster')),
            ],
        ),
        migrations.CreateModel(
            name='RosterSheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='module_roster.batch')),
                ('roster_day', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='module_roster.rosterday')),
                ('shift', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='module_roster.shift')),
            ],
        ),
        migrations.AddField(
            model_name='rosterday',
            name='roster',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='module_roster.roster'),
        ),
        migrations.AddField(
            model_name='batch',
            name='roster',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='module_roster.roster'),
        ),
    ]
