# Generated by Django 3.2.4 on 2021-07-08 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('module_appraisal', '0003_alter_appraisal_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='appraisal',
            name='appraisal_name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
