# Generated by Django 3.2.4 on 2021-07-09 03:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('module_employees', '0006_alter_employee_id'),
        ('module_appraisal', '0004_appraisal_appraisal_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appraisal',
            name='employee',
        ),
        migrations.CreateModel(
            name='AppraisalForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('knowledge', models.BooleanField()),
                ('work_quality', models.BooleanField()),
                ('productivity', models.BooleanField()),
                ('dependability', models.BooleanField()),
                ('attendace', models.BooleanField()),
                ('relations', models.BooleanField()),
                ('rating', models.BooleanField()),
                ('appraisal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='module_appraisal.appraisal')),
                ('employee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='module_employees.employee')),
            ],
        ),
    ]
