# Generated by Django 3.2.4 on 2021-07-09 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('module_appraisal', '0006_auto_20210709_0442'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appraisalform',
            name='attendace',
        ),
        migrations.AddField(
            model_name='appraisalform',
            name='attendance',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='appraisalform',
            name='dependability',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='appraisalform',
            name='knowledge',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='appraisalform',
            name='productivity',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='appraisalform',
            name='rating',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='appraisalform',
            name='relations',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='appraisalform',
            name='work_quality',
            field=models.BooleanField(null=True),
        ),
    ]
