# Generated by Django 3.0.6 on 2021-04-02 06:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Procurement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_code', models.CharField(blank=True, max_length=20)),
                ('order_date', models.DateField(blank=True, null=True)),
                ('order_type', models.CharField(blank=True, max_length=100)),
                ('description', models.TextField(blank=True)),
                ('project', models.CharField(blank=True, max_length=100)),
                ('recepient', models.CharField(blank=True, max_length=100)),
                ('vendor', models.CharField(blank=True, max_length=100)),
                ('vendor_phone', models.CharField(blank=True, max_length=20)),
                ('vendor_email', models.CharField(blank=True, max_length=100)),
                ('vendor_address', models.TextField(blank=True)),
                ('order_status', models.CharField(blank=True, max_length=20)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Profile')),
            ],
        ),
    ]
