# Generated by Django 3.0.6 on 2021-04-01 04:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Leave',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leave_code', models.CharField(blank=True, max_length=20)),
                ('date_requested', models.DateField(blank=True, null=True)),
                ('leave_type', models.CharField(blank=True, max_length=50)),
                ('from_date', models.DateField(blank=True, null=True)),
                ('to_date', models.DateField(blank=True, null=True)),
                ('duration', models.CharField(blank=True, max_length=20)),
                ('reason', models.TextField(blank=True)),
                ('status', models.CharField(blank=True, max_length=50)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Profile')),
            ],
        ),
    ]
