# Generated by Django 3.0.6 on 2021-05-11 05:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('module_employees', '0002_employee_photo'),
        ('module_leave', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='leave',
            name='employee',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='module_employees.Employee'),
        ),
    ]
