# Generated by Django 3.0.6 on 2021-04-25 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('module_drugs', '0004_auto_20210324_1016'),
        ('module_dispensary', '0002_auto_20210324_0846'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Detail',
            new_name='DispensaryDrug',
        ),
    ]
