# Generated by Django 3.0.6 on 2021-03-24 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('module_nurses', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='nurse',
            old_name='hospital',
            new_name='account',
        ),
    ]
