# Generated by Django 3.0.6 on 2021-04-24 18:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('module_nurses', '0002_auto_20210324_0920'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nurse',
            name='ended_work',
        ),
        migrations.RemoveField(
            model_name='nurse',
            name='started_work',
        ),
        migrations.RemoveField(
            model_name='nurse',
            name='work_status',
        ),
    ]
