# Generated by Django 3.0.6 on 2021-04-24 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('module_nurses', '0003_auto_20210424_1846'),
    ]

    operations = [
        migrations.AddField(
            model_name='nurse',
            name='photo',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
