# Generated by Django 3.0.6 on 2021-01-24 09:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('module_patients', '0003_auto_20210119_0225'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ward',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ward_number', models.CharField(blank=True, max_length=50)),
                ('ward_name', models.CharField(blank=True, max_length=100)),
                ('ward_type', models.CharField(blank=True, max_length=50)),
                ('location', models.TextField(blank=True)),
                ('capacity', models.IntegerField(blank=True)),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Profile')),
            ],
        ),
        migrations.CreateModel(
            name='WardPatient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bed_number', models.CharField(blank=True, max_length=20)),
                ('date_admitted', models.DateField(blank=True, null=True)),
                ('date_discharged', models.DateField(blank=True, null=True)),
                ('status', models.CharField(blank=True, max_length=50)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='module_patients.Patient')),
                ('ward', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='module_wards.Ward')),
            ],
        ),
    ]
