# Generated by Django 3.0.6 on 2021-03-12 20:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('module_students', '0001_initial'),
        ('module_parents', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParentWard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='module_parents.Parent')),
                ('ward', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='module_students.Student')),
            ],
        ),
    ]
