# Generated by Django 3.0.6 on 2021-05-03 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('module_parents', '0002_parentward'),
    ]

    operations = [
        migrations.AddField(
            model_name='parent',
            name='photo',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
