# Generated by Django 3.0.6 on 2021-06-13 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('module_parents', '0003_parent_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parent',
            name='photo',
            field=models.FileField(null=True, upload_to='parents'),
        ),
    ]
