# Generated by Django 3.0.6 on 2021-03-31 06:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('module_assets', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='asset',
            old_name='serail_number',
            new_name='serial_number',
        ),
    ]
