# Generated by Django 3.0.6 on 2021-05-06 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('module_teachers', '0002_teacher_date_of_birth'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='photo',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
