# Generated by Django 3.0.6 on 2021-06-13 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('module_teachers', '0003_teacher_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='photo',
            field=models.FileField(null=True, upload_to='teachers'),
        ),
    ]
