# Generated by Django 3.0.6 on 2021-04-14 20:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Purchasing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purchasing_code', models.CharField(blank=True, max_length=20)),
                ('purchasing_date', models.DateField(blank=True, null=True)),
                ('supplier_name', models.CharField(blank=True, max_length=100)),
                ('supplier_contact', models.CharField(blank=True, max_length=100)),
                ('supplier_invoice', models.CharField(blank=True, max_length=30)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Profile')),
            ],
        ),
        migrations.CreateModel(
            name='PurchasingItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(blank=True, max_length=100)),
                ('quantity', models.CharField(blank=True, max_length=20)),
                ('total_price', models.CharField(blank=True, max_length=20)),
                ('purchasing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='module_purchasing.Purchasing')),
            ],
        ),
    ]
