# Generated by Django 3.2.4 on 2021-06-18 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('module_purchasing', '0002_remove_purchasing_supplier_invoice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchasing',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='purchasingitem',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
