# Generated by Django 3.2.4 on 2021-07-12 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('module_purchasing', '0003_auto_20210618_2007'),
    ]

    operations = [
        migrations.RenameField(
            model_name='purchasingitem',
            old_name='item',
            new_name='item_description',
        ),
        migrations.RemoveField(
            model_name='purchasingitem',
            name='total_price',
        ),
    ]
