# Generated by Django 3.0.6 on 2021-04-03 00:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Folder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('folder_name', models.CharField(max_length=100, null=True)),
                ('folder_number', models.CharField(max_length=50, null=True)),
                ('date_created', models.DateField(auto_now_add=True, null=True)),
                ('last_updated', models.DateField(auto_now=True, null=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Profile')),
            ],
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=100, null=True)),
                ('file_number', models.CharField(max_length=50, null=True)),
                ('date_created', models.DateField(auto_now_add=True, null=True)),
                ('folder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='module_files.Folder')),
            ],
        ),
    ]
