# Generated by Django 3.0.6 on 2021-05-12 06:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('module_files', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='file',
            old_name='date_created',
            new_name='date_added',
        ),
    ]
