# Generated by Django 3.0.6 on 2021-03-21 21:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('module_doctors', '0002_auto_20210120_0957'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doctor',
            old_name='hospital',
            new_name='account',
        ),
    ]
