# Generated by Django 3.0.6 on 2021-04-23 04:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('module_doctors', '0003_auto_20210321_2116'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='ended_work',
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='started_work',
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='work_status',
        ),
    ]
