# Generated by Django 3.0.6 on 2021-04-24 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('module_doctors', '0004_auto_20210423_0449'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='photo',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
