# Generated by Django 3.0.6 on 2021-06-13 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('module_doctors', '0005_doctor_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='photo',
            field=models.FileField(null=True, upload_to='doctors'),
        ),
    ]
