# Generated by Django 3.2.4 on 2021-06-19 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('module_attendance', '0002_alter_attendance_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='from_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='attendance',
            name='to_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
