# Generated by Django 3.2.4 on 2021-07-09 08:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('module_attendance', '0004_attendanceday_attendancesheet'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendancesheet',
            name='checks',
        ),
        migrations.CreateModel(
            name='AttendanceCheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check', models.BooleanField(null=True)),
                ('day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='module_attendance.attendanceday')),
            ],
        ),
    ]
