# Generated by Django 3.2.4 on 2021-07-09 08:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('module_employees', '0006_alter_employee_id'),
        ('module_attendance', '0005_auto_20210709_0829'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AttendanceSheet',
            new_name='AttendanceEmployee',
        ),
        migrations.AddField(
            model_name='attendancecheck',
            name='attendance_employee',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='module_attendance.attendanceemployee'),
            preserve_default=False,
        ),
    ]
