# Generated by Django 3.2.4 on 2021-07-09 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('module_attendance', '0007_alter_attendancecheck_day'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancecheck',
            name='time_in',
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name='attendancecheck',
            name='time_out',
            field=models.TimeField(null=True),
        ),
    ]
