# Generated by Django 3.0.6 on 2021-02-06 19:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reservation_code', models.CharField(blank=True, max_length=50)),
                ('reservation_date', models.DateTimeField(blank=True, null=True)),
                ('customer_name', models.CharField(blank=True, max_length=100)),
                ('number_guests', models.IntegerField(blank=True)),
                ('number_tables', models.IntegerField(blank=True)),
                ('arrival_date', models.DateTimeField(blank=True, null=True)),
                ('reservation_status', models.CharField(blank=True, max_length=50)),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Profile')),
            ],
        ),
    ]
