# Generated by Django 3.0.6 on 2021-01-24 17:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Drug',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ndc_number', models.CharField(blank=True, max_length=50)),
                ('drug_name', models.CharField(blank=True, max_length=100)),
                ('generic_name', models.CharField(blank=True, max_length=100)),
                ('category', models.CharField(blank=True, max_length=100)),
                ('unit_dose', models.CharField(blank=True, max_length=100)),
                ('drug_type', models.CharField(blank=True, max_length=100)),
                ('unit_price', models.CharField(blank=True, max_length=20)),
                ('batch_number', models.CharField(blank=True, max_length=50)),
                ('purchased_date', models.DateField(blank=True, null=True)),
                ('initial_quantity', models.CharField(blank=True, max_length=20)),
                ('dispensed_quantity', models.CharField(blank=True, max_length=20)),
                ('remaining_quantity', models.CharField(blank=True, max_length=20)),
                ('manufactured_date', models.DateField(blank=True, null=True)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('storage_location', models.CharField(blank=True, max_length=100)),
                ('storage_bin', models.CharField(blank=True, max_length=50)),
                ('refill_ordered', models.CharField(blank=True, max_length=20)),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Profile')),
            ],
        ),
    ]
