# Generated by Django 3.0.6 on 2021-01-24 21:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('module_drugs', '0002_drug_manufacturer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='drug',
            old_name='manufactured_date',
            new_name='manufacturing_date',
        ),
    ]
