# Generated by Django 3.0.6 on 2021-03-24 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('module_drugs', '0003_auto_20210124_2112'),
    ]

    operations = [
        migrations.RenameField(
            model_name='drug',
            old_name='hospital',
            new_name='account',
        ),
    ]
