# Generated by Django 3.0.6 on 2021-01-23 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('module_diagnosis', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='diagnosis',
            name='blood_group',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='diagnosis',
            name='blood_pressure',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='diagnosis',
            name='diagnosis_detail',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='diagnosis',
            name='height',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='diagnosis',
            name='pulse',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='diagnosis',
            name='remarks',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='diagnosis',
            name='temperature',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='diagnosis',
            name='treatment',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='diagnosis',
            name='weight',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.DeleteModel(
            name='Detail',
        ),
    ]
