# Generated by Django 3.0.6 on 2020-10-21 09:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20200930_0805'),
        ('module_portal', '0002_auto_20201020_1250'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rink',
            name='recipient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='rink_recipient', to='users.Profile'),
        ),
        migrations.AlterField(
            model_name='rink',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='rink_sender', to='users.Profile'),
        ),
    ]
