# Generated by Django 3.0.6 on 2020-07-30 13:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('module_budget', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Income',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_description', models.CharField(max_length=100)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=11)),
                ('budget', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='module_budget.Budget')),
            ],
        ),
        migrations.CreateModel(
            name='Expenditure',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_description', models.CharField(max_length=100)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=11)),
                ('budget', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='module_budget.Budget')),
            ],
        ),
    ]
