# Generated by Django 3.0.6 on 2020-07-31 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('module_budget', '0002_expenditure_income'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budget',
            name='budget_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='budget',
            name='budget_type',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='expenditure',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=11, null=True),
        ),
        migrations.AlterField(
            model_name='expenditure',
            name='item_description',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='income',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=11, null=True),
        ),
        migrations.AlterField(
            model_name='income',
            name='item_description',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
