# Generated by Django 3.0.6 on 2020-08-13 18:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('module_budget', '0003_auto_20200731_0914'),
    ]

    operations = [
        migrations.RenameField(
            model_name='expenditure',
            old_name='item_description',
            new_name='item',
        ),
        migrations.RenameField(
            model_name='income',
            old_name='item_description',
            new_name='item',
        ),
    ]
