# Generated by Django 3.0.6 on 2021-02-08 06:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('module_deliveries', '0001_initial'),
        ('accounts', '0001_initial'),
        ('module_orders', '0001_initial'),
        ('module_sittings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bill_code', models.CharField(blank=True, max_length=50)),
                ('bill_date', models.DateField(blank=True, null=True)),
                ('bill_type', models.CharField(blank=True, max_length=50)),
                ('customer_name', models.CharField(blank=True, max_length=100)),
                ('delivery', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='module_deliveries.Delivery')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='module_orders.Order')),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Profile')),
                ('sitting', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='module_sittings.Sitting')),
            ],
        ),
    ]
