# Generated by Django 3.0.6 on 2021-02-27 05:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('module_admin', '0002_access_activity'),
    ]

    operations = [
        migrations.RenameField(
            model_name='activity',
            old_name='module',
            new_name='activity_module',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='account',
            new_name='hospital',
        ),
    ]
