# Generated by Django 3.0.6 on 2021-03-30 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('module_payroll', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payroll',
            name='date_generated',
            field=models.DateField(blank=True, null=True),
        ),
    ]
