# Generated by Django 3.0.6 on 2021-03-30 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('module_payroll', '0002_auto_20210330_0525'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payroll',
            name='date_generated',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
