# Generated by Django 3.2.4 on 2021-06-18 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('module_payroll', '0003_auto_20210330_0535'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payroll',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
