# Generated by Django 3.2.4 on 2021-07-07 19:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('module_employees', '0006_alter_employee_id'),
        ('module_payroll', '0007_alter_payroll_date_generated'),
    ]

    operations = [
        migrations.CreateModel(
            name='PayrollSheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_name', models.CharField(max_length=100, null=True)),
                ('account_number', models.CharField(max_length=30, null=True)),
                ('pay_grade', models.CharField(max_length=30, null=True)),
                ('basic_pay', models.CharField(max_length=15, null=True)),
                ('salary', models.CharField(max_length=15, null=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='module_employees.employee')),
                ('payroll', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='module_payroll.payroll')),
            ],
        ),
    ]
