# Generated by Django 3.2.4 on 2021-07-07 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('module_payroll', '0008_payrollsheet'),
    ]

    operations = [
        migrations.AddField(
            model_name='payrollsheet',
            name='allowance',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='payrollsheet',
            name='tax',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
