# Generated by Django 3.2.4 on 2021-07-07 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('module_payroll', '0009_auto_20210707_1947'),
    ]

    operations = [
        migrations.AddField(
            model_name='payroll',
            name='payroll_code',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
