# Generated by Django 3.0.6 on 2021-05-24 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('module_members', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='member_code',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
