# Generated by Django 3.0.6 on 2020-08-12 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('module_notes', '0002_auto_20200812_1116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='body',
            field=models.TextField(null=True),
        ),
    ]
