# Generated by Django 3.2.4 on 2021-08-31 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('module_notes', '0004_auto_20210618_1943'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notefile',
            name='file',
            field=models.FileField(upload_to='notes'),
        ),
    ]
