# Generated by Django 3.0.6 on 2021-03-08 19:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Term',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term_name', models.CharField(blank=True, max_length=100)),
                ('term_begins', models.DateField(blank=True, null=True)),
                ('term_ends', models.DateField(blank=True, null=True)),
                ('academic_year', models.CharField(blank=True, max_length=50)),
                ('term_status', models.CharField(blank=True, max_length=20)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Profile')),
            ],
        ),
    ]
