# Generated by Django 3.2.4 on 2021-07-03 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('module_orders', '0003_auto_20210618_1957'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_total',
            field=models.CharField(blank=True, max_length=15),
        ),
    ]
