# Generated by Django 3.2.4 on 2021-07-12 13:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('module_cashflow', '0003_auto_20210712_1239'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeeklyOutflow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('outflow', models.CharField(blank=True, max_length=150)),
                ('week_one', models.CharField(blank=True, max_length=18)),
                ('week_two', models.CharField(blank=True, max_length=18)),
                ('week_three', models.CharField(blank=True, max_length=18)),
                ('week_four', models.CharField(blank=True, max_length=18)),
                ('week_five', models.CharField(blank=True, max_length=18)),
                ('cashflow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='module_cashflow.cashflow')),
            ],
        ),
        migrations.CreateModel(
            name='WeeklyInflow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inflow', models.CharField(blank=True, max_length=150)),
                ('week_one', models.CharField(blank=True, max_length=18)),
                ('week_two', models.CharField(blank=True, max_length=18)),
                ('week_three', models.CharField(blank=True, max_length=18)),
                ('week_four', models.CharField(blank=True, max_length=18)),
                ('week_five', models.CharField(blank=True, max_length=18)),
                ('cashflow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='module_cashflow.cashflow')),
            ],
        ),
        migrations.CreateModel(
            name='QuarterlyOutflow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('outflow', models.CharField(blank=True, max_length=150)),
                ('first_quarter', models.CharField(blank=True, max_length=18)),
                ('second_quarter', models.CharField(blank=True, max_length=18)),
                ('third_quarter', models.CharField(blank=True, max_length=18)),
                ('fourth_quarter', models.CharField(blank=True, max_length=18)),
                ('cashflow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='module_cashflow.cashflow')),
            ],
        ),
        migrations.CreateModel(
            name='QuarterlyInflow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inflow', models.CharField(blank=True, max_length=150)),
                ('first_quarter', models.CharField(blank=True, max_length=18)),
                ('second_quarter', models.CharField(blank=True, max_length=18)),
                ('third_quarter', models.CharField(blank=True, max_length=18)),
                ('fourth_quarter', models.CharField(blank=True, max_length=18)),
                ('cashflow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='module_cashflow.cashflow')),
            ],
        ),
        migrations.CreateModel(
            name='MonthlyOutflow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('outflow', models.CharField(blank=True, max_length=150)),
                ('january', models.CharField(blank=True, max_length=18)),
                ('february', models.CharField(blank=True, max_length=18)),
                ('march', models.CharField(blank=True, max_length=18)),
                ('april', models.CharField(blank=True, max_length=18)),
                ('may', models.CharField(blank=True, max_length=18)),
                ('june', models.CharField(blank=True, max_length=18)),
                ('july', models.CharField(blank=True, max_length=18)),
                ('august', models.CharField(blank=True, max_length=18)),
                ('september', models.CharField(blank=True, max_length=18)),
                ('october', models.CharField(blank=True, max_length=18)),
                ('november', models.CharField(blank=True, max_length=18)),
                ('december', models.CharField(blank=True, max_length=18)),
                ('cashflow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='module_cashflow.cashflow')),
            ],
        ),
        migrations.CreateModel(
            name='MonthlyInflow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inflow', models.CharField(blank=True, max_length=150)),
                ('january', models.CharField(blank=True, max_length=18)),
                ('february', models.CharField(blank=True, max_length=18)),
                ('march', models.CharField(blank=True, max_length=18)),
                ('april', models.CharField(blank=True, max_length=18)),
                ('may', models.CharField(blank=True, max_length=18)),
                ('june', models.CharField(blank=True, max_length=18)),
                ('july', models.CharField(blank=True, max_length=18)),
                ('august', models.CharField(blank=True, max_length=18)),
                ('september', models.CharField(blank=True, max_length=18)),
                ('october', models.CharField(blank=True, max_length=18)),
                ('november', models.CharField(blank=True, max_length=18)),
                ('december', models.CharField(blank=True, max_length=18)),
                ('cashflow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='module_cashflow.cashflow')),
            ],
        ),
        migrations.CreateModel(
            name='DailyOutflow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('outflow', models.CharField(blank=True, max_length=150)),
                ('monday', models.CharField(blank=True, max_length=18)),
                ('tuesday', models.CharField(blank=True, max_length=18)),
                ('friday', models.CharField(blank=True, max_length=18)),
                ('thursday', models.CharField(blank=True, max_length=18)),
                ('wednesday', models.CharField(blank=True, max_length=18)),
                ('cashflow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='module_cashflow.cashflow')),
            ],
        ),
        migrations.CreateModel(
            name='DailyInflow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inflow', models.CharField(blank=True, max_length=150)),
                ('monday', models.CharField(blank=True, max_length=18)),
                ('tuesday', models.CharField(blank=True, max_length=18)),
                ('friday', models.CharField(blank=True, max_length=18)),
                ('thursday', models.CharField(blank=True, max_length=18)),
                ('wednesday', models.CharField(blank=True, max_length=18)),
                ('cashflow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='module_cashflow.cashflow')),
            ],
        ),
    ]
