# Generated by Django 3.0.6 on 2021-04-05 18:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_number', models.CharField(blank=True, max_length=20)),
                ('room_type', models.CharField(blank=True, max_length=50)),
                ('location', models.TextField(blank=True)),
                ('rate', models.CharField(blank=True, max_length=15)),
                ('features', models.TextField(blank=True)),
                ('room_status', models.CharField(blank=True, max_length=20)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Profile')),
            ],
        ),
    ]
