# Generated by Django 3.2.4 on 2021-07-11 17:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('module_roster', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rostersheet',
            name='roster_day',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='module_roster.rosterday'),
            preserve_default=False,
        ),
    ]
