# Generated by Django 3.2.4 on 2021-07-11 17:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('module_roster', '0002_rostersheet_roster_day'),
    ]

    operations = [
        migrations.AddField(
            model_name='rostersheet',
            name='batch',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='module_roster.batch'),
        ),
        migrations.AddField(
            model_name='rostersheet',
            name='shift',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='module_roster.shift'),
        ),
        migrations.AlterField(
            model_name='rostersheet',
            name='roster_day',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='module_roster.rosterday'),
        ),
    ]
