# Generated by Django 3.0.6 on 2021-06-02 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('module_sales', '0002_auto_20210602_2033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sales',
            name='sales_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
