# Generated by Django 3.0.6 on 2021-02-02 03:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('module_menu', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='menuitem',
            old_name='hospital',
            new_name='restaurant',
        ),
    ]
