# Generated by Django 3.0.6 on 2021-03-24 19:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('module_menu', '0002_auto_20210202_0336'),
    ]

    operations = [
        migrations.RenameField(
            model_name='menuitem',
            old_name='restaurant',
            new_name='account',
        ),
    ]
