# Generated by Django 3.2.4 on 2021-07-10 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('module_services', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='service_code',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='service',
            name='service_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='service_type',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='service',
            name='total_amount',
            field=models.CharField(blank=True, max_length=18),
        ),
    ]
