# Generated by Django 3.2.4 on 2021-07-10 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('module_services', '0003_serviceitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceitem',
            name='amount',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='serviceitem',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
