# Generated by Django 3.0.6 on 2021-03-27 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('module_admin', '0003_auto_20210324_1919'),
    ]

    operations = [
        migrations.AddField(
            model_name='access',
            name='sittings_access',
            field=models.BooleanField(default=False),
        ),
    ]
