# Generated by Django 3.2.4 on 2021-08-20 06:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_profile_logo'),
        ('module_admin', '0005_auto_20210618_1957'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('personal', models.PositiveIntegerField()),
                ('invitation_status', models.BooleanField(default=False)),
                ('date_sent', models.DateTimeField(auto_now=True, null=True)),
                ('date_confirmed', models.DateTimeField(null=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.profile')),
            ],
        ),
        migrations.DeleteModel(
            name='Activity',
        ),
    ]
