# Generated by Django 3.2.4 on 2021-08-23 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('module_admin', '0007_alter_invitation_invitation_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invitation',
            old_name='personal',
            new_name='personal_id',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_admin',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_manager',
        ),
        migrations.AddField(
            model_name='user',
            name='user_level',
            field=models.BooleanField(max_length=20, null=True),
        ),
    ]
