# Generated by Django 3.0.6 on 2021-04-27 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('module_admissions', '0002_auto_20210324_1041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admission',
            name='admission_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='admission',
            name='discharge_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
