# Generated by Django 3.0.6 on 2021-03-07 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('module_admin', '0002_auto_20210307_0552'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='school',
            new_name='account',
        ),
    ]
