# Generated by Django 3.0.6 on 2021-03-27 21:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('module_admin', '0003_auto_20210324_1919'),
    ]

    operations = [
        migrations.RenameField(
            model_name='access',
            old_name='admissions_access',
            new_name='aassets_access',
        ),
        migrations.RenameField(
            model_name='access',
            old_name='appointments_access',
            new_name='accounts_access',
        ),
        migrations.RenameField(
            model_name='access',
            old_name='bills_access',
            new_name='appraisal_access',
        ),
        migrations.RenameField(
            model_name='access',
            old_name='diagnosis_access',
            new_name='attendance_access',
        ),
        migrations.RenameField(
            model_name='access',
            old_name='dispensary_access',
            new_name='budget_access',
        ),
        migrations.RenameField(
            model_name='access',
            old_name='doctors_access',
            new_name='employees_access',
        ),
        migrations.RenameField(
            model_name='access',
            old_name='drugs_access',
            new_name='files_access',
        ),
        migrations.RenameField(
            model_name='access',
            old_name='laboratory_access',
            new_name='leave_access',
        ),
        migrations.RenameField(
            model_name='access',
            old_name='nurses_access',
            new_name='ledger_access',
        ),
        migrations.RenameField(
            model_name='access',
            old_name='patients_access',
            new_name='letters_access',
        ),
        migrations.RenameField(
            model_name='access',
            old_name='payments_access',
            new_name='payroll_access',
        ),
        migrations.RenameField(
            model_name='access',
            old_name='prescriptions_access',
            new_name='procurement_access',
        ),
        migrations.RenameField(
            model_name='access',
            old_name='staff_access',
            new_name='reception_access',
        ),
        migrations.RemoveField(
            model_name='access',
            name='wards_access',
        ),
    ]
