# Generated by Django 3.0.6 on 2021-04-05 07:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('module_admin', '0004_auto_20210327_2153'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='access',
            name='aassets_access',
        ),
        migrations.RemoveField(
            model_name='access',
            name='accounts_access',
        ),
        migrations.RemoveField(
            model_name='access',
            name='appraisal_access',
        ),
        migrations.RemoveField(
            model_name='access',
            name='attendance_access',
        ),
        migrations.RemoveField(
            model_name='access',
            name='budget_access',
        ),
        migrations.RemoveField(
            model_name='access',
            name='employees_access',
        ),
        migrations.RemoveField(
            model_name='access',
            name='files_access',
        ),
        migrations.RemoveField(
            model_name='access',
            name='leave_access',
        ),
        migrations.RemoveField(
            model_name='access',
            name='ledger_access',
        ),
        migrations.RemoveField(
            model_name='access',
            name='letters_access',
        ),
        migrations.RemoveField(
            model_name='access',
            name='payroll_access',
        ),
        migrations.RemoveField(
            model_name='access',
            name='procurement_access',
        ),
        migrations.RemoveField(
            model_name='access',
            name='reception_access',
        ),
    ]
