# Generated by Django 3.0.6 on 2021-06-02 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('module_customers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='customer_type',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
