# Generated by Django 3.0.6 on 2021-05-03 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('module_customers', '0002_auto_20210324_2200'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='photo',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
