# Generated by Django 3.0.6 on 2021-04-10 17:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campaign_code', models.CharField(blank=True, max_length=20)),
                ('campaign_name', models.CharField(blank=True, max_length=100)),
                ('campaign_type', models.CharField(blank=True, max_length=50)),
                ('target_audience', models.TextField(blank=True)),
                ('campaign_status', models.CharField(blank=True, max_length=30)),
                ('supervisor', models.CharField(blank=True, max_length=100)),
                ('goals', models.TextField(blank=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Profile')),
            ],
        ),
    ]
