# Generated by Django 3.0.6 on 2021-01-20 15:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('module_patients', '0003_auto_20210119_0225'),
        ('module_doctors', '0002_auto_20210120_0957'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appointment_code', models.CharField(blank=True, max_length=50)),
                ('appointment_date', models.DateField(blank=True)),
                ('appointment_for', models.CharField(blank=True, max_length=100)),
                ('remarks', models.TextField(blank=True, max_length=100)),
                ('appointment_status', models.CharField(blank=True, choices=[('Scheduled', 'Scheduled'), ('Ongoning', 'Ongoing'), ('Finished', 'Finished'), ('Canceled', 'Canceled')], max_length=50)),
                ('consultant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='module_doctors.Doctor')),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Profile')),
                ('patient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='module_patients.Patient')),
            ],
        ),
    ]
