# Generated by Django 3.0.6 on 2021-01-21 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('module_appointments', '0002_auto_20210120_1713'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='appointment_status',
            field=models.CharField(blank=True, choices=[('Scheduled', 'Scheduled'), ('Ongoing', 'Ongoing'), ('Finished', 'Finished'), ('Canceled', 'Canceled')], max_length=50),
        ),
    ]
