# Generated by Django 3.0.6 on 2021-01-22 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('module_appointments', '0003_auto_20210121_1823'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='appointment_status',
            field=models.CharField(blank=True, choices=[('Scheduled', 'Scheduled'), ('Ongoing', 'Ongoing'), ('Finished', 'Finished'), ('Cancelled', 'Cancelled')], max_length=50),
        ),
    ]
