# Generated by Django 3.0.6 on 2021-03-21 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('module_appointments', '0004_auto_20210122_1032'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointment',
            old_name='hospital',
            new_name='account',
        ),
    ]
