# Generated by Django 3.0.6 on 2021-03-10 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('module_classes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='location',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
