# Generated by Django 3.0.6 on 2021-05-05 05:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('module_terms', '0001_initial'),
        ('module_teachers', '0002_teacher_date_of_birth'),
        ('module_classes', '0002_auto_20210310_0527'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='class_teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='module_teachers.Teacher'),
        ),
        migrations.AddField(
            model_name='class',
            name='term',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='module_terms.Term'),
        ),
    ]
