# Generated by Django 3.0.6 on 2021-05-06 05:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('module_terms', '0001_initial'),
        ('module_timetables', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='timetable',
            name='term',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='module_terms.Term'),
        ),
    ]
