# Generated by Django 3.2.4 on 2021-07-01 05:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('module_classes', '0004_auto_20210618_1959'),
        ('module_timetables', '0004_auto_20210618_1959'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timetableclass',
            name='clas',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='module_classes.class'),
        ),
    ]
