# Generated by Django 3.2.4 on 2021-07-01 18:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('module_timetables', '0005_alter_timetableclass_clas'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimetableSheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subjects', models.JSONField()),
                ('timetable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='module_timetables.timetable')),
                ('timetable_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='module_timetables.timetableclass')),
                ('timetable_period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='module_timetables.timetableperiod')),
            ],
        ),
    ]
