# Generated by Django 3.0.6 on 2021-03-14 11:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('module_classes', '0002_auto_20210310_0527'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_code', models.CharField(blank=True, max_length=20)),
                ('report_name', models.CharField(blank=True, max_length=100)),
                ('report_date', models.DateField(blank=True, null=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Profile')),
                ('clas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='module_classes.Class')),
            ],
        ),
    ]
