# Generated by Django 3.2.4 on 2021-06-27 23:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('module_assessment', '0006_auto_20210618_1959'),
        ('module_reports', '0003_alter_report_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportAssessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assessment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='module_assessment.assessment')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='module_reports.report')),
            ],
        ),
    ]
