# Generated by Django 3.2.4 on 2021-06-28 20:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('module_students', '0004_alter_student_id'),
        ('module_reports', '0004_reportassessment'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportStudent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='module_reports.report')),
                ('student', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='module_students.student')),
            ],
        ),
    ]
