# Generated by Django 3.2.4 on 2021-07-05 05:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('module_students', '0004_alter_student_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='clas',
        ),
    ]
