# Generated by Django 3.2.4 on 2021-07-05 06:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('module_classes', '0006_auto_20210705_0602'),
        ('module_students', '0005_remove_student_clas'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='clas',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='module_classes.class'),
        ),
    ]
