# Generated by Django 3.0.6 on 2021-06-04 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('module_materials', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='material',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='material',
            name='unit_price',
        ),
    ]
