# Generated by Django 3.0.6 on 2021-01-20 02:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('module_staff', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staff',
            name='occupation',
        ),
    ]
