# Generated by Django 3.0.6 on 2021-01-20 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('module_staff', '0002_remove_staff_occupation'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='ended_work',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='staff',
            name='started_work',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='staff',
            name='work_status',
            field=models.CharField(blank=True, choices=[('Active', 'Active'), ('Transfered', 'Transfered'), ('Retired', 'Retired')], max_length=50),
        ),
    ]
