# Generated by Django 3.0.6 on 2021-03-24 10:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('module_staff', '0003_auto_20210120_0957'),
    ]

    operations = [
        migrations.RenameField(
            model_name='staff',
            old_name='hospital',
            new_name='account',
        ),
    ]
