# Generated by Django 3.0.6 on 2021-04-24 20:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('module_staff', '0004_auto_20210324_1004'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staff',
            name='ended_work',
        ),
        migrations.RemoveField(
            model_name='staff',
            name='started_work',
        ),
        migrations.RemoveField(
            model_name='staff',
            name='work_status',
        ),
    ]
