# Generated by Django 3.2.4 on 2021-06-25 21:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('module_roster', '0003_batch_rosterdays_rostersheet_shift_staffpersonnel'),
    ]

    operations = [
        migrations.CreateModel(
            name='RosterDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateField(blank=True, null=True)),
                ('roster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='module_roster.roster')),
            ],
        ),
        migrations.DeleteModel(
            name='RosterDays',
        ),
    ]
