# Generated by Django 3.2.4 on 2021-06-27 08:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('module_roster', '0004_auto_20210625_2128'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rostersheet',
            old_name='batch',
            new_name='batches',
        ),
    ]
