# Generated by Django 3.2.4 on 2021-06-18 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('module_ledger', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ledger',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='ledgeritem',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
