# Generated by Django 3.0.6 on 2021-05-24 21:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('module_members', '0002_member_member_code'),
        ('module_executives', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='executive',
            name='member',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='module_members.Member'),
        ),
    ]
