# Generated by Django 3.0.6 on 2021-05-24 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('module_executives', '0002_auto_20210524_2147'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='executive',
            name='committee_name',
        ),
        migrations.RemoveField(
            model_name='executive',
            name='committee_status',
        ),
        migrations.RemoveField(
            model_name='executive',
            name='description',
        ),
        migrations.RemoveField(
            model_name='executive',
            name='functions',
        ),
        migrations.AlterField(
            model_name='executive',
            name='position',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
