# Generated by Django 3.2.4 on 2021-07-11 05:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('module_bills', '0003_auto_20210618_2006'),
        ('module_payments', '0003_rename_amount_paid_payment_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='bill',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='module_bills.bill'),
        ),
    ]
