# Generated by Django 3.0.6 on 2021-01-30 12:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('module_patients', '0003_auto_20210119_0225'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patient',
            old_name='hospital',
            new_name='profile',
        ),
    ]
