# Generated by Django 3.0.6 on 2021-01-30 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('module_patients', '0004_auto_20210130_1234'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patient',
            old_name='profile',
            new_name='hospital',
        ),
    ]
