# Generated by Django 3.0.6 on 2021-03-21 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('module_patients', '0005_auto_20210130_1237'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patient',
            old_name='hospital',
            new_name='account',
        ),
    ]
