# Generated by Django 3.0.6 on 2021-06-13 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('module_patients', '0008_auto_20210613_1116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='photo',
            field=models.FileField(null=True, upload_to='patients'),
        ),
    ]
