# Generated by Django 3.0.6 on 2021-03-13 17:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('module_subjects', '0002_remove_subject_term'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assessment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assessment_code', models.CharField(blank=True, max_length=20)),
                ('assessment_name', models.CharField(blank=True, max_length=100)),
                ('assessment_date', models.DateField(blank=True, null=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Profile')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='module_subjects.Subject')),
            ],
        ),
    ]
