# Generated by Django 3.2.4 on 2021-06-16 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('module_assessment', '0003_assessment_clas'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssessmentSheet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sheet', models.JSONField()),
            ],
        ),
    ]
