# Generated by Django 3.2.4 on 2021-06-16 20:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('module_students', '0003_auto_20210613_1551'),
        ('module_assessment', '0004_assessmentsheet'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assessmentsheet',
            name='sheet',
        ),
        migrations.AddField(
            model_name='assessmentsheet',
            name='assessment',
            field=models.ForeignKey(default=7, on_delete=django.db.models.deletion.CASCADE, to='module_assessment.assessment'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='assessmentsheet',
            name='grade',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='assessmentsheet',
            name='remarks',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='assessmentsheet',
            name='score',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='assessmentsheet',
            name='student',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='module_students.student'),
            preserve_default=False,
        ),
    ]
