# Generated by Django 3.0.6 on 2021-04-15 20:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('module_products', '0001_initial'),
        ('module_manufacturing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='manufacturing',
            name='product',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='module_products.Product'),
            preserve_default=False,
        ),
    ]
