# Generated by Django 3.0.6 on 2021-06-04 12:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('module_products', '0001_initial'),
        ('module_manufacturing', '0002_manufacturing_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manufacturing',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='module_products.Product'),
        ),
    ]
