# Generated by Django 3.0.6 on 2021-06-02 02:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('module_products', '0002_auto_20210410_1200'),
        ('module_invoice', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoiceitem',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='module_products.Product'),
        ),
    ]
