# Generated by Django 3.0.6 on 2021-03-24 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('module_payments', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='hospital',
            new_name='account',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='admission',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='patient',
        ),
    ]
