# Generated by Django 3.0.6 on 2021-04-26 20:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('module_payments', '0002_auto_20210324_1129'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='amount_paid',
            new_name='payment',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='balance',
        ),
    ]
