# Generated by Django 3.0.6 on 2021-06-13 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('module_workers', '0002_worker_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worker',
            name='photo',
            field=models.FileField(null=True, upload_to='workers'),
        ),
    ]
