# Generated by Django 3.0.6 on 2021-05-07 05:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('module_fees', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fee',
            old_name='fee_code',
            new_name='fees_code',
        ),
        migrations.RenameField(
            model_name='fee',
            old_name='fee_date',
            new_name='fees_date',
        ),
        migrations.RenameField(
            model_name='fee',
            old_name='fee_description',
            new_name='fees_description',
        ),
    ]
