# Generated by Django 3.0.6 on 2021-05-09 20:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('module_fees', '0002_auto_20210507_0508'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeesItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(blank=True, max_length=100)),
                ('amount', models.CharField(blank=True, max_length=15)),
                ('fee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='module_fees.Fee')),
            ],
        ),
    ]
