# Generated by Django 3.2.4 on 2021-07-04 18:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('module_classes', '0004_auto_20210618_1959'),
        ('module_fees', '0004_auto_20210618_1959'),
    ]

    operations = [
        migrations.CreateModel(
            name='TargetClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='module_classes.class')),
                ('fee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='module_fees.fee')),
            ],
        ),
    ]
