# Generated by Django 3.2.4 on 2021-07-05 05:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('module_students', '0005_remove_student_clas'),
        ('module_fees', '0006_arrearsitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arrearsitem',
            name='source',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='source', to='module_fees.fee'),
        ),
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.CharField(blank=True, max_length=15)),
                ('fee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='module_fees.fee')),
                ('student', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='module_students.student')),
            ],
        ),
    ]
