# Generated by Django 3.0.6 on 2021-06-04 17:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('module_materials', '0002_auto_20210604_1710'),
        ('module_stock', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stockitem',
            name='material_name',
        ),
        migrations.AddField(
            model_name='stockitem',
            name='material',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='module_materials.Material'),
        ),
    ]
