# Generated by Django 3.0.6 on 2021-03-24 20:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('module_staff', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='staff',
            old_name='restaurant',
            new_name='account',
        ),
    ]
