# Generated by Django 3.0.6 on 2021-04-29 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('module_staff', '0002_auto_20210324_2000'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staff',
            name='ended_work',
        ),
        migrations.RemoveField(
            model_name='staff',
            name='started_work',
        ),
        migrations.RemoveField(
            model_name='staff',
            name='work_status',
        ),
        migrations.AddField(
            model_name='staff',
            name='photo',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
