# Generated by Django 3.0.6 on 2021-06-13 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('module_staff', '0003_auto_20210429_0401'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='photo',
            field=models.FileField(null=True, upload_to='staff'),
        ),
    ]
