# Generated by Django 3.0.6 on 2021-03-24 19:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('module_admin', '0002_auto_20210228_2120'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='restaurant',
            new_name='account',
        ),
    ]
