# Generated by Django 3.0.6 on 2021-05-13 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('module_employees', '0003_auto_20210513_0636'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='photo',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
