# Generated by Django 3.2.4 on 2021-07-12 09:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('module_staff', '0004_alter_staff_id'),
        ('module_roster', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_name', models.CharField(blank=True, max_length=100)),
                ('batch_symbol', models.CharField(blank=True, max_length=20)),
                ('roster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='module_roster.roster')),
            ],
        ),
        migrations.CreateModel(
            name='RosterDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateField(blank=True, null=True)),
                ('roster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='module_roster.roster')),
            ],
        ),
        migrations.CreateModel(
            name='StaffPersonnel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='module_roster.batch')),
                ('roster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='module_roster.roster')),
                ('staff', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='module_staff.staff')),
            ],
        ),
        migrations.CreateModel(
            name='Shift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shift_name', models.CharField(blank=True, max_length=100)),
                ('start_time', models.TimeField(null=True)),
                ('end_time', models.TimeField(null=True)),
                ('roster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='module_roster.roster')),
            ],
        ),
        migrations.CreateModel(
            name='RosterSheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='module_roster.batch')),
                ('roster_day', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='module_roster.rosterday')),
                ('shift', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='module_roster.shift')),
            ],
        ),
    ]
