# Generated by Django 3.0.6 on 2021-04-02 06:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference_number', models.CharField(blank=True, max_length=50)),
                ('letter_date', models.CharField(blank=True, max_length=20)),
                ('recipient', models.CharField(blank=True, max_length=20)),
                ('subject', models.CharField(blank=True, max_length=20)),
                ('date_sent', models.CharField(blank=True, max_length=20)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Profile')),
            ],
        ),
        migrations.CreateModel(
            name='Received',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference_number', models.CharField(blank=True, max_length=50)),
                ('letter_date', models.CharField(blank=True, max_length=20)),
                ('sender', models.CharField(blank=True, max_length=20)),
                ('subject', models.CharField(blank=True, max_length=20)),
                ('date_received', models.CharField(blank=True, max_length=20)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Profile')),
            ],
        ),
    ]
