# Generated by Django 3.0.6 on 2021-05-11 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('module_letters', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='received',
            name='date_received',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='received',
            name='letter_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='received',
            name='sender',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='received',
            name='subject',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='sent',
            name='date_sent',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='sent',
            name='letter_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='sent',
            name='recipient',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='sent',
            name='subject',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
