# Generated by Django 3.0.6 on 2021-02-24 05:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rink_date', models.DateTimeField(auto_now_add=True)),
                ('rink_type', models.CharField(max_length=50, null=True)),
                ('rink_source', models.IntegerField(null=True)),
                ('comment', models.TextField()),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='rink_recipient', to='accounts.Profile')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='rink_sender', to='accounts.Profile')),
            ],
        ),
    ]
