# Generated by Django 3.2.4 on 2021-07-07 04:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_alter_profile_id'),
        ('module_terms', '0002_alter_term_id'),
        ('module_classes', '0006_auto_20210705_0602'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attendance_code', models.CharField(blank=True, max_length=20)),
                ('attendance_name', models.CharField(blank=True, max_length=100)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.profile')),
                ('source', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='module_classes.class')),
                ('term', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='module_terms.term')),
            ],
        ),
    ]
