# Generated by Django 3.2.4 on 2021-06-18 20:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('module_terms', '0002_alter_term_id'),
        ('accounts', '0002_alter_profile_id'),
        ('module_classes', '0004_auto_20210618_1959'),
        ('module_students', '0004_alter_student_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attendance_code', models.CharField(blank=True, max_length=20)),
                ('attendance_name', models.CharField(blank=True, max_length=100)),
                ('from_date', models.DateField(blank=True, null=True)),
                ('to_date', models.DateField(blank=True, null=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.profile')),
                ('source', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='module_classes.class')),
                ('term', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='module_terms.term')),
            ],
        ),
        migrations.CreateModel(
            name='AttendanceSheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checks', models.JSONField()),
                ('attendance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='module_attendance.attendance')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='module_students.student')),
            ],
        ),
        migrations.CreateModel(
            name='AttendanceDays',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('days', models.JSONField()),
                ('attendance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='module_attendance.attendance')),
            ],
        ),
    ]
