# Generated by Django 3.0.6 on 2021-05-03 16:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('module_terms', '0001_initial'),
        ('module_classes', '0002_auto_20210310_0527'),
        ('module_attendance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='term',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='module_terms.Term'),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='source',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='module_classes.Class'),
        ),
    ]
