# Generated by Django 3.2.4 on 2021-07-07 04:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('module_attendance', '0003_attendancesheet'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('days', models.JSONField()),
                ('attendance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='module_attendance.attendance')),
            ],
        ),
    ]
