# Generated by Django 3.2.4 on 2021-07-07 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('module_attendance', '0004_attendanceday'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendanceday',
            name='days',
        ),
        migrations.AddField(
            model_name='attendanceday',
            name='day',
            field=models.DateField(blank=True, null=True),
        ),
    ]
