# Generated by Django 3.2.4 on 2021-07-09 12:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('module_students', '0006_student_clas'),
        ('module_attendance', '0005_auto_20210707_0527'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceCheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateField(blank=True, null=True)),
                ('check', models.BooleanField(null=True)),
                ('time_in', models.TimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='AttendanceStudent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attendance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='module_attendance.attendance')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='module_students.student')),
            ],
        ),
        migrations.DeleteModel(
            name='AttendanceSheet',
        ),
        migrations.AddField(
            model_name='attendancecheck',
            name='attendance_student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='module_attendance.attendancestudent'),
        ),
    ]
