# Generated by Django 3.0.6 on 2021-04-25 05:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('module_prescriptions', '0002_auto_20210324_0933'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Detail',
            new_name='PrescriptionDetail',
        ),
    ]
