# Generated by Django 3.2.4 on 2021-07-02 07:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('module_nurses', '0006_alter_nurse_id'),
        ('module_staff', '0008_alter_staff_id'),
        ('module_roster', '0004_doctorspersonnel_rosterdays_rostersheet'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RosterDays',
            new_name='RosterDay',
        ),
        migrations.CreateModel(
            name='StaffPersonnel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='module_roster.batch')),
                ('roster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='module_roster.roster')),
                ('staff', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='module_staff.staff')),
            ],
        ),
        migrations.CreateModel(
            name='NursesPersonnel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='module_roster.batch')),
                ('nurse', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='module_nurses.nurse')),
                ('roster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='module_roster.roster')),
            ],
        ),
    ]
