# Generated by Django 3.2.4 on 2021-07-03 06:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('module_roster', '0005_auto_20210702_0704'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rosterday',
            old_name='days',
            new_name='day',
        ),
    ]
