# Generated by Django 3.2.4 on 2021-07-03 06:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('module_roster', '0006_rename_days_rosterday_day'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rostersheet',
            old_name='batch',
            new_name='batches',
        ),
    ]
