# Generated by Django 3.0.6 on 2021-03-08 21:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('module_subjects', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject',
            name='term',
        ),
    ]
