# Generated by Django 3.0.6 on 2021-06-03 18:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('module_purchasing', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchasing',
            name='supplier_invoice',
        ),
    ]
