# Generated by Django 3.2.4 on 2021-07-12 08:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('module_purchasing', '0004_auto_20210618_2006'),
    ]

    operations = [
        migrations.RenameField(
            model_name='purchasing',
            old_name='purchasing_number',
            new_name='purchasing_code',
        ),
        migrations.RemoveField(
            model_name='purchasingitem',
            name='total_price',
        ),
    ]
