# Generated by Django 3.0.6 on 2021-05-06 20:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('module_teachers', '0003_teacher_photo'),
        ('module_students', '0002_student_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_name', models.CharField(blank=True, max_length=100)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Profile')),
                ('teacher', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='module_teachers.Teacher')),
            ],
        ),
        migrations.CreateModel(
            name='SectionStudents',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='module_sections.Section')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='module_students.Student')),
            ],
        ),
    ]
