# Generated by Django 3.2.4 on 2021-07-02 04:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('module_students', '0004_alter_student_id'),
        ('module_sections', '0002_auto_20210618_1959'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SectionStudents',
            new_name='SectionStudent',
        ),
    ]
