# Generated by Django 3.0.6 on 2021-04-09 04:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('module_rooms', '0001_initial'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Housekeeping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('housekeeping_code', models.CharField(blank=True, max_length=20)),
                ('housekeeping_date', models.DateField(blank=True, null=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Profile')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='module_rooms.Room')),
            ],
        ),
        migrations.CreateModel(
            name='Checklist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_number', models.CharField(blank=True, max_length=20)),
                ('item_description', models.CharField(blank=True, max_length=100)),
                ('status', models.BooleanField(blank=True, null=True)),
                ('remarks', models.TextField(blank=True)),
                ('housekeeping', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='module_housekeeping.Housekeeping')),
            ],
        ),
    ]
