# Generated by Django 3.0.6 on 2021-06-01 19:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('module_rooms', '0001_initial'),
        ('module_housekeeping', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='housekeeping',
            name='room',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='module_rooms.Room'),
        ),
    ]
