# Generated by Django 3.0.6 on 2021-01-22 10:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('module_doctors', '0002_auto_20210120_0957'),
        ('module_patients', '0003_auto_20210119_0225'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Laboratory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lab_code', models.CharField(blank=True, max_length=50)),
                ('lab_date', models.DateField(blank=True, null=True)),
                ('lab_type', models.CharField(blank=True, max_length=100)),
                ('doctor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='module_doctors.Doctor')),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Profile')),
                ('patient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='module_patients.Patient')),
            ],
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_code', models.CharField(blank=True, max_length=50)),
                ('test_name', models.CharField(blank=True, max_length=100)),
                ('remarks', models.TextField(blank=True)),
                ('laboratory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='module_laboratory.Laboratory')),
            ],
        ),
    ]
