# Generated by Django 3.0.6 on 2021-01-23 20:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('module_laboratory', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Test',
        ),
    ]
