# Generated by Django 3.0.6 on 2021-03-24 08:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('module_laboratory', '0002_delete_test'),
    ]

    operations = [
        migrations.RenameField(
            model_name='laboratory',
            old_name='hospital',
            new_name='account',
        ),
    ]
