# Generated by Django 3.0.6 on 2021-04-24 00:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('module_laboratory', '0003_auto_20210324_0823'),
    ]

    operations = [
        migrations.CreateModel(
            name='LaboratoryFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attachment', models.FileField(blank=True, upload_to='')),
                ('laboratory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='module_laboratory.Laboratory')),
            ],
        ),
    ]
