# Generated by Django 3.0.6 on 2021-04-24 07:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('module_laboratory', '0004_laboratoryfile'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='LaboratoryFile',
            new_name='Attachment',
        ),
    ]
