# Generated by Django 3.2.4 on 2021-06-18 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('module_calendar', '0002_auto_20200731_0914'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
