# Generated by Django 3.0.6 on 2021-02-06 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('module_stock', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockitem',
            name='quantity',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='stockitem',
            name='refill_ordered',
            field=models.IntegerField(blank=True),
        ),
    ]
