# Generated by Django 3.0.6 on 2021-03-24 20:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('module_stock', '0002_auto_20210206_1955'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stockitem',
            old_name='restaurant',
            new_name='account',
        ),
    ]
