# Generated by Django 3.0.6 on 2021-04-10 19:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('module_receivables', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='receivable',
            old_name='date_paid',
            new_name='date_received',
        ),
    ]
