# Generated by Django 3.0.6 on 2021-06-02 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('module_receivables', '0002_auto_20210410_1931'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receivable',
            name='date_received',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='receivable',
            name='due_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='receivable',
            name='receivable_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
