# Generated by Django 3.0.6 on 2021-05-24 07:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_activity', models.CharField(blank=True, max_length=100)),
                ('meeting_date', models.DateField(null=True)),
                ('meeting_time', models.TimeField(null=True)),
                ('location', models.CharField(blank=True, max_length=100)),
                ('all_activities', models.TextField(blank=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Profile')),
            ],
        ),
    ]
