# Generated by Django 3.2.4 on 2021-08-24 12:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_profile_logo'),
        ('module_settings', '0003_auto_20210824_1157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extendedprofile',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='extendedprofile',
            name='profile',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.profile'),
        ),
    ]
