# Generated by Django 3.0.6 on 2021-04-29 04:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('module_payments', '0002_auto_20210324_2014'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='balance',
        ),
    ]
